stages:
  - build
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.16.0
    entrypoint: [""]
  script:
  - |
    cat > /kaniko/.docker/config.json <<EOF
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth":"${DOCKER_AUTH}"
        },
        "${CI_REGISTRY}": {
          "username": "${CI_REGISTRY_USER}",
          "password": "${CI_REGISTRY_PASSWORD}"
        }
      }
    }
    EOF
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination koehn/diaspora:$CI_COMMIT_TAG --build-arg GIT_BRANCH=$(echo $CI_COMMIT_TAG | awk -F '-' '{print $1}') --build-arg SCANNER_TOKEN=$SCANNER_TOKEN
  only: 
  - tags

build_latest:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - |
    cat > /kaniko/.docker/config.json <<EOF
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth":"${DOCKER_AUTH}"
        },
        "${CI_REGISTRY}": {
          "username": "${CI_REGISTRY_USER}",
          "password": "${CI_REGISTRY_PASSWORD}"
        }
      }
    }
    EOF
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination koehn/diaspora:latest --build-arg SCANNER_TOKEN=$SCANNER_TOKEN
  only: 
  - tags

deploy:
  stage: deploy
  image:
    name: koehn/alpine-ssh
  script:
  - mkdir -p /root/.ssh
  - chmod 700 /root/.ssh
  - cat $TURNKEY_FP > /root/.ssh/known_hosts
  - cat $SSH_PRIVATE_KEY > /root/.ssh/id_rsa
  - cat $SSH_PUBLIC_KEY > /root/.ssh/id_rsa.pub
  - chmod 600 /root/.ssh/known_hosts /root/.ssh/id_rsa /root/.ssh/id_rsa.pub
  - ssh root@turnkey.koehn.com "cd /home/docker/docker-services/web/sites/diaspora && docker-compose pull & docker-compose up -d"
