build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - |
    cat > /kaniko/.docker/config.json <<EOF
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth":"${DOCKER_AUTH}"
        },
        "${CI_REGISTRY}": {
          "username": "${CI_REGISTRY_USER}",
          "password": "${CI_REGISTRY_PASSWORD}"
        }
      }
    }
    EOF
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination koehn/diaspora:$CI_COMMIT_TAG --build-arg GIT_BRANCH=$CI_COMMIT_TAG --build-arg SCANNER_TOKEN=$SCANNER_TOKEN
  only: 
  - tags

build_latest:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
  - |
    cat > /kaniko/.docker/config.json <<EOF
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth":"${DOCKER_AUTH}"
        },
        "${CI_REGISTRY}": {
          "username": "${CI_REGISTRY_USER}",
          "password": "${CI_REGISTRY_PASSWORD}"
        }
      }
    }
    EOF
  - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination koehn/docker:latest --build-arg SCANNER_TOKEN=$SCANNER_TOKEN
  only: 
  - tags

